language: node_js

node_js:
  - '6'
  - '4'

install:
  - npm install

script:
  - npm run build

notifications:
  email: false

deploy:
  provider: npm
  email: trevinhofmann@gmail.com
  on:
    tags: true
    node: '6'
  api_key:
    secure: "LtvZ+IZc15VzYxH33/VhAh5cLyaGFTHKRdBEkFTfDhIuvN/dKq9nlpAPJkKT3hAM5z45/MKBe3LbmwWd/6Da9mXRACzE1yhXze+brf4BShw7smURpvT/aYi5p2cHOr70rv2wnABrbQl2LFLsEZkrJv62ec9+NuRXQhUH/vPbEIkDrlJFheUJ2KXpCFv1YaIoNfrEJ9t6Kst6rp+8ehK9+5owHVNDj8PB2ATqcxxlk3nvgBa7UqjIbxi1jbW/ToCDAPSB8KA3NmmR+NxfrhlsCy784mv63CLwUhYCBQdxMmjpi2ITzlU3ZZU40FWUUgYZpc4pqS/hfYVTLGZm23eBs5x07I85DbsBOHJ6EvJuhBYPgae/gMtSRD3N/67ftLIPq7qmLV0HevxJ0QoMUB2XvOMPYR8s/Q5Z4nA+adGFVeaiZyeusEQ24VGwpJz02v3e17KElzVR3nwQNwN1JB57+u9/4eD33EO24ul29E0BmSXiRZPSJk8IeTaL4VtBdq+0F4Xo4JhCQV+pV40SPlvrORZvyUrDT7Kcl52U0M8XPXNIobvA4XUrWWzhKSx6bStqu1OVQzkgX5EHTTqyph4LNg9yu9BWVw0FJjMJ7CCB0QTcZcfYmqZXe93F3j23ddBUwYisV4Ps6Su5yFtQ1/rrJ70MWPP/gzqsU/colR8H3Zw="
