language: node_js

node_js:
  - '6'
  - '4'

install:
  - npm install

script:
  - npm run build

notifications:
  email: false

deploy:
  provider: npm
  email: trevinhofmann@gmail.com
  on:
    tags: true
    node: '6'
  api_key:
    secure: "Ih92ST+qSI40BrRHNgmRHLbEYxZ/9svnLXrDft4wli10V3EGznYIrqDqOh/qFdVdgble3Aq9xRZvTarM5D1lWc0D0wlQQNroMhpGMFbLDDaEE2tWVIw8D/Nn/Vx1oVUUSJllL4vpzmExwJuq374v8QMjrMzt/viXaHW5abjsum9Tm3BCs0lzxmn7y6fW1TG3qYbJiS7CWhIR95/9LRTQNFITeCkbNNA5UqMVp0a3/SF18BcTZEil8ZMHUCoROX2MjKFZN+t+PTy0IC6B3oYgCBHU1BceIqTGKRMj+ofrwmdG8KLknoD8gxGd5Eaf8vxjalEWn2GYtCV6rIe2fgcb57ICUfdOK16bm1gAPm5CWQbYO94bHKmSXk4TTRLRCAyN13pIPTuSwDmxxaxYwJ7OAgr+IS3ywy/RbnFywHY5vDI/B8ga1YEV3dTYGvMEjrSVFjTUuhTVzJ470Z3YnrLiUr+Nq56ELENZfR6s0d4UMUoCBUxhkJuvSF88VnQ2qVR/5eUnT2DoFuROcRXnfUen2dz+yw5DoSo0+HSJ350MmhCs7JkfMJfj5iIg218LbQ3MuVHZcl0vZ6oICdekGLAEmGrYFfnTIhwwnn5VVWXMx/OMsjgtDIHV3yLYqNLfpI7/8m24Wqtb0yEwyKxqdWXfsHykia8GX5mC+3y0cXunkGg="
