language: node_js

node_js:
  - '6'
  - '4'

install:
  - npm install

script:
  - npm run build

notifications:
  email: false

deploy:
  provider: npm
  email: trevinhofmann@gmail.com
  on:
    tags: true
    node: '6'
  api_key:
    secure: gUYB6LSvaXPG+dLtw52RNuSGtBzb2B1/y18FXOjBd8qALolXyousRb70lw6cYmDACB2pjwrG5X4KhPozlAMLU6G1lYh/BVVSePyeDRyU85mf+Kyqrob9oh9UJS0FhqVR/oNJoCkKIIZ6PVO2NJAgm45154EkQwsJHHan752+Z3qkJcMvfd9Xvgg+lVPatjnU3ZXb7h6gM4CIQFdiPQxcPYxNYdJrgGpQCHPQTRS4BNlIIP/j1SeWB4K19QmaE1fKagsp0Hu0cLLWm40ULOl1r/eK0Ab09jZv9j6Uc6gDf+H3T1M0QbqhHm5bNhs6pz1qXnp2hrH1B521DIO+0xrjWIaXcc8Avv81JiT5HMpgVIMUDxI9prYO+ifp/0VwuXohS+9lmcE1IhcVuZg9j4JXDECUeFu/eD1bvPjiJG7nI7juLP0qGNTMuL3sdRe0sXEdGRWTNe9vd0gz/aypOg1WplRTLPNO3WUHqilTc05UUpA1p+g3q1+t/zaPmCTkdpA8fde+UjSIWIjaxDpvbSvaSDbtwli7lzv03sH9uFIZWY0S+dkloQCtSTH4XXyQ97H4JUwuCHeLVMj1J62pZUnpi8EoKF7SwvXQBx97eQzPzbcF7J/2h38zFzon14yli30CZLplmp4WSYEMOOTJy3J5+oqE/W60iFySLxrEsnKaT0s=
